# Website Settings

# Import Theme
theme: jekyll-theme-chirpy

# Site Language › https://www.w3.org/International/questions/qa-choosing-language-tags
# If a file with the same name exists under the folder `_data/locales`, the layout language will also change,
# Otherwise, the layout language uses the default value 'en'.
lang: en

# Modify to your time zone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/Denver

# jekyll-seo-tag Settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# --------------------------
title: Sindi      # Main Title

tagline: Every day is a chance to learn more. # Subtitle

description: >- # Used by seo meta and atom feed
  Sindi's personal blog

# Fill in the protocol and domain of your website.
# For example, 'https://username.github.io', note not to end with '/'.
url: "https://bandsind.github.io"

author: Sindi Banda # Full name

github:
  username: Bandsind # Github Username

#twitter:
  #username: Bandas # Twitter Username

social:
  # Change to your full name.
  # This will be displayed as the default author of posts and the copyright owner in the footer
  name: Sindi Banda
  email: Sindikani321@gmail.com # Email Address
  links:
    # The first link will be used as the copyright owner's link
    - https://sindi.cc
    - https://github.com/Bandsind 
    #- https://twitter.com/NichtsHsu # Twitter Homepage
    # Github Homepage
    # Uncomment to add more links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification: # Enter your verification string

# ↑ --------------------------
# `jekyll-seo-tag` settings end

google_analytics:
  id: # Enter your Google Analytics ID

# Set preferred color scheme
#
# Tip: Leaving blank will follow the system's default preferred color scheme, and a button to switch between light and dark themes will appear at the bottom of the sidebar.
#
# Available options:
#
#     light  - Use light scheme
#     dark   - Use dark scheme
#
theme_mode: # [light|dark]

# Enable animated background effect
backgroud_animation: false

# Enable mouse click effect
mouse_click_effect: false

# Image CDN endpoint.
# Note that once assigned, CDN URL will be added to
# all images starting with '/' (website avatar and images in posts)
# 
# For example, 'https://cdn.com'
img_cdn: ""

# Sidebar avatar, supports local or CROS resources
avatar: /avatar.png

# Set content displayed on the right sidebar
panel:
  # Set the content displayed in the right sidebar of posts
  # 
  # Tip:
  #   Global switch to false will definitely not display the corresponding block.
  #   Global switch to true allows turning off the right sidebar feature for individual posts using the md file header like:
  #      lastmod: false
  #   for that post.
  post:
    # Recently Updated
    lastmod: true
    # Trending Tags
    trending_tags: true
    # External Links
    external_links: true
    # Table of Contents
    toc: true

comments:
  active: # Global switch for post comments, for example, 'disqus'. Leave empty to disable
  # The active option can be as follows:
  # disqus commenting system > https://disqus.com/
  disqus:
    shortname: # Enter your disqus shortname › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances commenting system › https://utteranc.es/
  utterances:
    repo: # <Github Username>/<Repository Name>
    issue_term: # < Link | Path | Title | ...>
  # Waline commenting system › https://waline.js.org/
  waline:
    server: # Vercal server address
    placeholder: Say something! # Text displayed when the comment box is empty
    avatar: mp # Default avatar  › https://waline.js.org/guide/client/avatar.html
  # Giscus options › https://giscus.app
  giscus:
    repo: # <Github Username>/<Repository Name>
    repo_id:
    category:
    category_id:
    mapping: # Optional, default is 'pathname'
    input_position: # Optional, default is 'bottom'
    lang: # Optional, default is `site.lang` value
    reactions_enabled: # Optional, default is 1

# Self-host static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # Boolean, empty means no
    # Specify Jekyll environment, empty means all are enabled
    # Only effective when `assets.self_host.enabled` is 'true'
    env: # [development|production]

pwa:
  enabled: true # PWA feature option

# Number of posts per page
paginate: 10

# Base URL of the website
baseurl: ""

# ------------ Below settings are not recommended to modify ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge settings › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts
      # Default display for the right sidebar
      lastmod: true
      trending_tags: true
      external_links: true
      toc: true
      license: true
      # Don't change it unless you are an expert in Jekyll and Web development,
      # or you think you are smart enough to modify it to another relative path in this template.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # Refer to `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/